(()=>{
'use strict';
if(window.__CGMA_NATIVE_I18N_BOOTED)return;
window.__CGMA_NATIVE_I18N_BOOTED=true;
const LOCALE_KEY='ekodi_user_locale';
const LEGACY_KEY='ekodi-language';
const COOKIE_KEY='ekodi_locale';
const SUPPORTED=new Set(['ko-KR','en','zh-CN','ja','vi','ne']);
const COPY={
  'ko-KR':{title:'청계면상인회, 어디에 있어도 우리는 연결되어 있습니다',about:'상인회 소개',map:'상권지도',resources:'자료실',news:'상권소식',live:'온라인',login:'Google 로그인',join:'가입하기',liveKicker:'실시간 소통 공간',liveIntro:'정기회의와 온라인 임원회는 Jitsi에서, 현장 행사와 상권 소식은 YouTube에서 만납니다.',meetingTitle:'실시간 화상회의',meetingBody:'홈페이지 안에서 이름을 입력하고 회의에 참여할 수 있습니다. 카메라와 마이크는 참여자가 직접 허용할 때만 사용됩니다.',meetingOpen:'회의실을 새 창에서 열기 ↗',youtubeTitle:'YouTube 방송',youtubeBody:'라이브 중에는 실시간 영상을 보여주고, 방송이 없거나 임베드할 수 없을 때는 안전한 안내 카드로 전환합니다.',youtubeOpen:'YouTube 라이브 확인 ↗',home:'청계면상인회 홈',language:'언어 선택'},
  en:{title:'Cheonggye Merchants Association, Connected Wherever We Are',about:'About',map:'Market Map',resources:'Resources',news:'Market News',live:'Online',login:'Google Sign in',join:'Join',liveKicker:'Live connection space',liveIntro:'Meetings and online leadership sessions happen on Jitsi, while local events and market news are shared on YouTube.',meetingTitle:'Live video meeting',meetingBody:'Enter your name and join the meeting right here. Camera and microphone are used only after you grant permission.',meetingOpen:'Open meeting in a new window ↗',youtubeTitle:'YouTube Broadcast',youtubeBody:'A live stream appears here in real time. When no live stream is active, the latest broadcast is shown automatically; a safe status card appears only when embedding is unavailable.',youtubeOpen:'Check YouTube Live ↗',home:'Cheonggye Merchants Association home',language:'Choose language'},
  'zh-CN':{title:'清溪面商会，无论身在何处，我们始终相连',about:'商会介绍',map:'商圈地图',resources:'资料室',news:'商圈资讯',live:'在线',login:'Google 登录',join:'加入',liveKicker:'实时交流空间',liveIntro:'定期会议和线上理事会通过 Jitsi 进行，现场活动与商圈资讯通过 YouTube 分享。',meetingTitle:'实时视频会议',meetingBody:'可直接在网页中输入姓名并参加会议。摄像头和麦克风仅在您主动授权后使用。',meetingOpen:'在新窗口打开会议室 ↗',youtubeTitle:'YouTube 直播',youtubeBody:'直播开始时这里会显示实时画面；没有直播或无法嵌入时，会自动显示清晰的提示卡片。',youtubeOpen:'查看 YouTube 直播 ↗',home:'清溪面商会首页',language:'选择语言'},
  ja:{title:'清渓面商人会、どこにいても私たちはつながっています',about:'商人会紹介',map:'商圏マップ',resources:'資料室',news:'商圏ニュース',live:'オンライン',login:'Googleログイン',join:'参加する',liveKicker:'リアルタイム交流',liveIntro:'定例会議とオンライン役員会はJitsiで、現地イベントと商圏ニュースはYouTubeで共有します。',meetingTitle:'リアルタイム会議',meetingBody:'ページ内で名前を入力して会議に参加できます。カメラとマイクは許可した場合のみ使用されます。',meetingOpen:'会議室を新しいウィンドウで開く ↗',youtubeTitle:'YouTube配信',youtubeBody:'ライブ中は映像を表示し、配信がない時や埋め込み不可の場合は案内カードに切り替えます。',youtubeOpen:'YouTubeライブを確認 ↗',home:'清渓面商人会ホーム',language:'言語を選択'},
  vi:{title:'Hiệp hội Tiểu thương Cheonggye, luôn kết nối dù ở bất cứ đâu',about:'Giới thiệu',map:'Bản đồ khu phố',resources:'Tài liệu',news:'Tin khu phố',live:'Trực tuyến',login:'Đăng nhập Google',join:'Tham gia',liveKicker:'Không gian kết nối trực tiếp',liveIntro:'Các cuộc họp định kỳ diễn ra trên Jitsi, còn sự kiện và tin khu phố được chia sẻ trên YouTube.',meetingTitle:'Họp video trực tiếp',meetingBody:'Nhập tên và tham gia cuộc họp ngay trên trang. Camera và mic chỉ được dùng khi bạn cho phép.',meetingOpen:'Mở phòng họp trong cửa sổ mới ↗',youtubeTitle:'Phát sóng YouTube',youtubeBody:'Khi có livestream, video sẽ xuất hiện ở đây. Nếu chưa có hoặc không thể nhúng, trang sẽ chuyển sang thẻ hướng dẫn.',youtubeOpen:'Kiểm tra YouTube Live ↗',home:'Trang chủ Hiệp hội Tiểu thương Cheonggye',language:'Chọn ngôn ngữ'},
  ne:{title:'चेओन्ग्ये व्यापारी संघ, जहाँ भए पनि हामी सधैं जोडिएका छौं',about:'संघ परिचय',map:'बजार नक्सा',resources:'सामग्री',news:'बजार समाचार',live:'अनलाइन',login:'Google लगइन',join:'सदस्य बन्नुहोस्',liveKicker:'प्रत्यक्ष संवाद स्थान',liveIntro:'नियमित बैठक र अनलाइन नेतृत्व बैठक Jitsi मा हुन्छन्, स्थानीय कार्यक्रम र बजार समाचार YouTube मा साझा गरिन्छ।',meetingTitle:'प्रत्यक्ष भिडियो बैठक',meetingBody:'यही पृष्ठमा नाम लेखेर बैठकमा सहभागी हुन सकिन्छ। क्यामेरा र माइक्रोफोन तपाईंले अनुमति दिएपछि मात्र प्रयोग हुन्छ।',meetingOpen:'बैठक नयाँ विन्डोमा खोल्नुहोस् ↗',youtubeTitle:'YouTube प्रसारण',youtubeBody:'लाइभ हुँदा भिडियो यहाँ देखिन्छ। प्रसारण नभएको वा एम्बेड गर्न नसकिने अवस्थामा स्पष्ट जानकारी कार्ड देखाइन्छ।',youtubeOpen:'YouTube Live हेर्नुहोस् ↗',home:'चेओन्ग्ये व्यापारी संघ गृह',language:'भाषा छान्नुहोस्'}
};
const language=document.getElementById('siteLanguage');
function normalize(value){const raw=String(value||'').trim();if(SUPPORTED.has(raw))return raw;const lower=raw.toLowerCase();if(lower==='ko'||lower.startsWith('ko-'))return'ko-KR';if(lower==='zh'||lower.startsWith('zh-'))return'zh-CN';if(lower==='ja'||lower.startsWith('ja-'))return'ja';if(lower==='vi'||lower.startsWith('vi-'))return'vi';if(lower==='ne'||lower.startsWith('ne-'))return'ne';return'en';}
function controlLocale(locale){return locale==='ko-KR'?'ko':locale;}
function clearLegacyGoogleTranslate(){for(const domain of ['',`.${location.hostname}`]){const suffix=domain?`;domain=${domain}`:'';document.cookie=`googtrans=;path=/;max-age=0${suffix};SameSite=Lax`;}}
function ensureNativeBoundary(){let meta=document.head.querySelector('meta[name="google"][content="notranslate"]');if(!meta){meta=document.createElement('meta');meta.name='google';meta.content='notranslate';document.head.append(meta);}document.documentElement.dataset.ekodiBrowserTranslation='native-i18n';clearLegacyGoogleTranslate();}
function persist(locale){try{localStorage.setItem(LOCALE_KEY,locale);localStorage.removeItem(LEGACY_KEY);}catch{}try{document.cookie=`${COOKIE_KEY}=${encodeURIComponent(locale)};path=/;max-age=31536000;SameSite=Lax${location.protocol==='https:'?';Secure':''}`;}catch{}}
function setText(selector,value){const node=document.querySelector(selector);if(node&&node.textContent!==value)node.textContent=value;}
function applyCopy(locale){const c=COPY[locale]||COPY.en;document.documentElement.lang=locale;document.documentElement.dataset.ekodiLocale=locale;document.title=locale==='ko-KR'?`청계면상인회 | ${c.title}`:c.title;setText('.header nav a[href="#about"]',c.about);setText('.header nav a[href="#market-map"]',c.map);setText('.header nav a[href="#resources"]',c.resources);setText('.header nav a[href="#news"]',c.news);setText('.header nav a[href="#live"]',c.live);setText('.header nav [data-central-auth]',c.login);setText('.header nav [data-member-apply]',c.join);setText('.live-head > div > span:not(.live-dot)',c.liveKicker);setText('.live-head h2',c.title);setText('.live-head > p',c.liveIntro);setText('.meeting-room h3',c.meetingTitle);setText('.meeting-room .live-card-copy p',c.meetingBody);setText('.meeting-room .live-fallback',c.meetingOpen);setText('.youtube-live h3',c.youtubeTitle);setText('.youtube-live .live-card-copy p',c.youtubeBody);setText('.youtube-live .live-fallback',c.youtubeOpen);const brand=document.querySelector('.header .brand');if(brand)brand.setAttribute('aria-label',c.home);if(language)language.setAttribute('aria-label',c.language);}
function homeUrl(){const url=new URL(location.href);url.search='';url.hash='';url.pathname=(url.hostname==='ekodi.kr'||url.hostname==='www.ekodi.kr')?'/cgma/':'/';return url;}
function bindBrandHome(){const brand=document.querySelector('.header .brand');if(!brand)return;brand.dataset.ekodiHeaderHome='cgma';brand.href=homeUrl().toString();brand.addEventListener('click',event=>{const target=homeUrl(),here=new URL(location.href);here.search='';here.hash='';if(here.origin===target.origin&&here.pathname.replace(/\/+$/,'/')===target.pathname.replace(/\/+$/,'/')){event.preventDefault();window.scrollTo({top:0,left:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});try{history.replaceState(history.state,'',target.pathname+location.search);}catch{}}});}
function apply(value,{save=true,emit=true}={}){const locale=normalize(value);if(save)persist(locale);const control=controlLocale(locale);if(language&&language.value!==control)language.value=control;applyCopy(locale);if(emit)window.dispatchEvent(new CustomEvent('ekodi:locale-change',{detail:{locale,source:'cgma-native-i18n'}}));return locale;}
ensureNativeBoundary();bindBrandHome();let saved='';try{saved=localStorage.getItem(LOCALE_KEY)||localStorage.getItem(LEGACY_KEY)||'';}catch{}const initial=normalize(saved||document.documentElement.lang||navigator.language||'ko-KR');apply(initial,{save:true,emit:false});
language?.addEventListener('change',()=>{const locale=normalize(language.value);if(window.EKODIUserLanguage?.setLocale)window.EKODIUserLanguage.setLocale(locale);else apply(locale);});
window.addEventListener('ekodi:locale-change',event=>{const locale=normalize(event.detail?.locale);if(document.documentElement.dataset.ekodiLocale!==locale)apply(locale,{save:true,emit:false});else applyCopy(locale);});
window.CGMANativeI18n=Object.freeze({getLocale:()=>normalize(document.documentElement.dataset.ekodiLocale),setLocale:locale=>apply(locale)});
})();
