const API='https://renzehysxirjilvdxacv.supabase.co/functions/v1/core-api';
const TENANT='cheonggye';
const route=value=>window.CGMA_ROUTE?.route(value)||value;
const LABELS={all:'전체',food:'밥집·식당',snack:'분식·간식',fastfood:'치킨·패스트푸드',cafe:'카페·디저트',pub:'주점·펍',mart:'편의점·마트',service:'생활·서비스'};
let stores=[];let category='all';
const el=(id)=>document.getElementById(id);
const esc=(s)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function renderFilters(){el('filters').innerHTML=Object.entries(LABELS).map(([k,v])=>`<button data-cat="${k}" class="${k===category?'active':''}">${v}</button>`).join('');el('filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderFilters();renderStores();});}
function renderStores(){const q=el('search').value.trim().toLowerCase();const list=stores.filter(s=>(category==='all'||s.category===category)&&(!q||`${s.name} ${s.public_address||''} ${LABELS[s.category]||''}`.toLowerCase().includes(q)));el('count').textContent=`${list.length}개 점포`;el('status').hidden=list.length>0;el('status').textContent=list.length?'':'조건에 맞는 점포가 없습니다.';el('stores').innerHTML=list.map(s=>`<article class="store-card" tabindex="0" data-slug="${esc(s.slug)}"><span class="cat">${esc(LABELS[s.category]||s.category||'상점')}</span><h3>${esc(s.name)}</h3><p>${esc(s.public_address||'주소 확인 중')}</p>${s.order_enabled?'<span class="order-chip">QR 주문 가능</span>':''}</article>`).join('');el('stores').querySelectorAll('.store-card').forEach(card=>{const open=()=>openStore(card.dataset.slug);card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')open();};});}
async function openStore(slug){el('storeDetail').innerHTML='<p>매장 정보를 불러오는 중입니다.</p>';el('storeDialog').showModal();try{const r=await fetch(`${API}/public/stores/${encodeURIComponent(slug)}?tenant=${TENANT}`);if(!r.ok)throw new Error();const d=await r.json();const menu=d.menu||[];el('storeDetail').innerHTML=`<span class="eyebrow">${esc(LABELS[d.store.category]||'STORE')}</span><h2>${esc(d.store.name)}</h2><p class="addr">${esc(d.store.public_address||'')}</p>${menu.length?`<div class="menu-list">${menu.map(m=>`<div class="menu-item"><div><b>${esc(m.name)}</b><small>${esc(m.description||'')}</small></div><strong>${Number(m.price).toLocaleString()}원</strong></div>`).join('')}</div>${d.store.order_enabled?`<p style="margin-top:16px"><a class="order-link" href="${route(`/order/${encodeURIComponent(d.store.slug)}?source=market-ai`)}">이 매장 주문 · 결제 →</a></p>`:'<p class="empty-menu">온라인 주문은 매장 확인 후 순차적으로 엽니다.</p>'}`:'<div class="empty-menu">메뉴와 주문 기능은 정회원 매장부터 순차적으로 연결합니다.</div>'}`;}catch{el('storeDetail').innerHTML='<div class="empty-menu">매장 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</div>';}}
function initPilotChannelInputs(){const root=document.querySelector('[data-ekodi-marketing-pilot="cgma"]');if(!root)return;const prefix='ekodi-marketing-pilot:cgma:channel:';for(const row of root.querySelectorAll('.pilot-table tbody tr')){const cells=row.querySelectorAll('td');if(cells.length<7)continue;const type=(cells[0].textContent||'').trim();const addressCell=cells[2];if((addressCell.textContent||'').trim()!=='미확인')continue;const wrap=document.createElement('div');wrap.className='pilot-channel-edit';const input=document.createElement('input');input.type='url';input.placeholder='채널주소 입력';input.setAttribute('aria-label',`${type} 채널주소`);let saved='';try{saved=localStorage.getItem(prefix+type)||'';}catch{}if(saved){input.value=saved;cells[1].textContent='사용자 입력';cells[6].textContent='이 브라우저';}const button=document.createElement('button');button.type='button';button.textContent=saved?'저장됨':'임시저장';button.addEventListener('click',()=>{const value=input.value.trim();if(value&&!/^https:\/\//i.test(value)){input.setCustomValidity('https:// 로 시작하는 채널주소를 입력해 주세요.');input.reportValidity();return;}input.setCustomValidity('');try{if(value)localStorage.setItem(prefix+type,value);else localStorage.removeItem(prefix+type);}catch{}button.textContent=value?'저장됨':'임시저장';cells[1].textContent=value?'사용자 입력':'자동조사 대기';cells[6].textContent=value?'이 브라우저':'—';});wrap.append(input,button);addressCell.textContent='';addressCell.append(wrap);}}
async function trackQr(){const p=new URLSearchParams(location.search);const code=p.get('qr');if(!code)return;fetch(`${API}/public/qr-scan`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,source:p.get('source')||'market-ai-page'})}).catch(()=>{});}
async function init(){renderFilters();initPilotChannelInputs();el('search').addEventListener('input',renderStores);el('clearSearch').onclick=()=>{el('search').value='';renderStores();};el('dialogClose').onclick=()=>el('storeDialog').close();try{const r=await fetch(`${API}/public/stores?tenant=${TENANT}`);if(!r.ok)throw new Error();const d=await r.json();stores=d.stores||[];el('status').hidden=true;renderStores();}catch{el('status').hidden=false;el('status').textContent='상권 데이터를 불러오지 못했습니다.';el('count').textContent='연결 확인 필요';}trackQr();}
document.addEventListener('DOMContentLoaded',init);
