const API='https://renzehysxirjilvdxacv.supabase.co/functions/v1/core-api';
const TENANT='cheonggye';
const LABELS={all:'전체',food:'밥집·식당',snack:'분식·간식',fastfood:'치킨·패스트푸드',cafe:'카페·디저트',pub:'주점·펍',mart:'편의점·마트',service:'생활·서비스'};
let stores=[];let category='all';
const el=(id)=>document.getElementById(id);
const esc=(s)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function renderFilters(){el('filters').innerHTML=Object.entries(LABELS).map(([k,v])=>`<button data-cat="${k}" class="${k===category?'active':''}">${v}</button>`).join('');el('filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderFilters();renderStores();});}
function renderStores(){const q=el('search').value.trim().toLowerCase();const list=stores.filter(s=>(category==='all'||s.category===category)&&(!q||`${s.name} ${s.public_address||''} ${LABELS[s.category]||''}`.toLowerCase().includes(q)));el('count').textContent=`${list.length}개 점포`;el('status').hidden=list.length>0;el('status').textContent=list.length?'':'조건에 맞는 점포가 없습니다.';el('stores').innerHTML=list.map(s=>`<article class="store-card" tabindex="0" data-slug="${esc(s.slug)}"><span class="cat">${esc(LABELS[s.category]||s.category||'상점')}</span><h3>${esc(s.name)}</h3><p>${esc(s.public_address||'주소 확인 중')}</p>${s.order_enabled?'<span class="order-chip">QR 주문 가능</span>':''}</article>`).join('');el('stores').querySelectorAll('.store-card').forEach(card=>{const open=()=>openStore(card.dataset.slug);card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')open();};});}
async function openStore(slug){el('storeDetail').innerHTML='<p>매장 정보를 불러오는 중입니다.</p>';el('storeDialog').showModal();try{const r=await fetch(`${API}/public/stores/${encodeURIComponent(slug)}?tenant=${TENANT}`);if(!r.ok)throw new Error();const d=await r.json();const menu=d.menu||[];el('storeDetail').innerHTML=`<span class="eyebrow">${esc(LABELS[d.store.category]||'STORE')}</span><h2>${esc(d.store.name)}</h2><p class="addr">${esc(d.store.public_address||'')}</p>${menu.length?`<div class="menu-list">${menu.map(m=>`<div class="menu-item"><div><b>${esc(m.name)}</b><small>${esc(m.description||'')}</small></div><strong>${Number(m.price).toLocaleString()}원</strong></div>`).join('')}</div>${d.store.order_enabled?'<p class="empty-menu">주문 장바구니와 결제 연결은 매장 PG 활성화 후 표시됩니다.</p>':''}`:'<div class="empty-menu">메뉴와 주문 기능은 정회원 매장부터 순차적으로 연결합니다.</div>'}`;}catch{el('storeDetail').innerHTML='<div class="empty-menu">매장 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</div>';}}
async function trackQr(){const p=new URLSearchParams(location.search);const code=p.get('qr');if(!code)return;fetch(`${API}/public/qr-scan`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,source:p.get('source')||'market-ai-page'})}).catch(()=>{});}
async function init(){renderFilters();el('search').addEventListener('input',renderStores);el('clearSearch').onclick=()=>{el('search').value='';renderStores();};el('dialogClose').onclick=()=>el('storeDialog').close();try{const r=await fetch(`${API}/public/stores?tenant=${TENANT}`);if(!r.ok)throw new Error();const d=await r.json();stores=d.stores||[];el('status').hidden=true;renderStores();}catch{el('status').hidden=false;el('status').textContent='상권 데이터를 불러오지 못했습니다.';el('count').textContent='연결 확인 필요';}trackQr();}
document.addEventListener('DOMContentLoaded',init);
