import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://renzehysxirjilvdxacv.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_';
const STORE_API=`${SUPABASE_URL}/functions/v1/store-api`;
const READINESS_API=`${SUPABASE_URL}/functions/v1/readiness-api`;
const PAYMENT_ADMIN=`${SUPABASE_URL}/functions/v1/payment-admin`;
const PROFILE_TABLE='store_public_profiles',MEDIA_BUCKET='cgma-store-media';
const sb=createClient(SUPABASE_URL,PUBLISHABLE_KEY,{auth:{flowType:'pkce',detectSessionInUrl:true,persistSession:true}});
const route=value=>window.CGMA_ROUTE?.route(value)||value;
const absolute=value=>window.CGMA_ROUTE?.absolute(value)||new URL(route(value),location.origin).toString();
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const won=n=>`${Number(n||0).toLocaleString('ko-KR')}원`;
let stores=[],currentStoreId=null,dashboard=null,readiness=null,editingMenu=null,publicProfile=null,profileHeroRemoved=false,storeInsights=null;
function show(id,on=true){$(id).classList.toggle('hide',!on)}
function setStatus(id,text,type=''){const e=$(id);e.textContent=text;e.className=`status${type?` ${type}`:''}`;e.classList.remove('hide')}
async function session(){const {data}=await sb.auth.getSession();return data.session}
async function api(path,options={},base=STORE_API){const s=await session();if(!s)throw new Error('login_required');const headers={apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${s.access_token}`,...(options.headers||{})};if(options.body)headers['content-type']='application/json';const r=await fetch(`${base}${path}`,{...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data.error||`http_${r.status}`);e.data=data;e.status=r.status;throw e}return data;}
async function insightsApi(){const s=await session();if(!s||!currentStoreId)return null;const endpoint=route(`/api/store-events?store_id=${encodeURIComponent(currentStoreId)}&days=7`),r=await fetch(endpoint,{headers:{Authorization:`Bearer ${s.access_token}`},cache:'no-store'}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`http_${r.status}`);return data;}

async function loadStores(){const d=await api('/stores');stores=d.stores||[];if(!stores.length){show('app',false);setStatus('loginStatus','승인된 점포가 없습니다. 먼저 정회원 페이지에서 내 가게 확인 신청을 완료해 주세요.','warn');show('loginCard',true);return}const select=$('storeSelect');select.innerHTML=stores.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');show('storeSelect',stores.length>1);show('refresh',true);show('logout',true);currentStoreId=currentStoreId&&stores.some(s=>s.id===currentStoreId)?currentStoreId:stores[0].id;select.value=currentStoreId;await loadDashboard();}
async function loadDashboard(){if(!currentStoreId)return;const [d,r,pf,ins]=await Promise.all([api(`/dashboard?store_id=${encodeURIComponent(currentStoreId)}`),api(`?store_id=${encodeURIComponent(currentStoreId)}`,{},READINESS_API).catch(()=>null),sb.from(PROFILE_TABLE).select('*').eq('store_id',currentStoreId).maybeSingle(),insightsApi().catch(()=>null)]);dashboard=d;readiness=r;publicProfile=pf.error?null:pf.data;storeInsights=ins;profileHeroRemoved=false;show('loginCard',false);show('app',true);renderDashboard();}

function renderDashboard(){const d=dashboard,s=d.store;$('storeName').textContent=s.name;$('storeAddress').textContent=s.public_address||'';const today=new Date().toISOString().slice(0,10);const todays=d.orders.filter(o=>String(o.created_at).slice(0,10)===today);$('todayOrders').textContent=todays.length;$('paidOrders').textContent=d.orders.filter(o=>o.payment?.status==='paid').length;$('activeOrders').textContent=d.orders.filter(o=>['confirmed','preparing','ready'].includes(o.status)).length;$('menuCount').textContent=d.menu.filter(m=>m.is_available&&m.verification_status==='verified').length;$('orderBadge').textContent=s.order_enabled?'주문 ON':'주문 OFF';$('orderBadge').className=`badge ${s.order_enabled?'confirmed':''}`;$('toggleOrdering').textContent=s.order_enabled?'주문 끄기':'주문 켜기';setStatus('storeStatus',s.order_enabled?'온라인 주문이 열려 있습니다.':'온라인 주문은 현재 닫혀 있습니다.',s.order_enabled?'':'warn');const storeQr=d.qr_codes.find(q=>q.kind==='store'&&q.active);if(storeQr){const url=absolute(`/order/${encodeURIComponent(s.slug)}?qr=${encodeURIComponent(storeQr.code)}&source=store-qr`);$('qrBox').innerHTML=`<b>매장 QR 연결주소</b><br><a href="${esc(url)}" target="_blank" rel="noopener">${esc(url)}</a>`;show('qrBox',true);$('openOrder').href=url;show('openOrder',true)}else{show('qrBox',false);$('openOrder').href=route(`/order/${encodeURIComponent(s.slug)}`);show('openOrder',s.order_enabled)}renderPublicProfile();renderInsights();renderReadiness();renderPendingMenus();renderMenu();renderOrders();}

function setProfilePreview(url){const box=$('profilePreview');box.innerHTML=url?`<img src="${esc(url)}" alt="대표사진 미리보기"/>`:'<span>대표사진 미등록</span>';}
function renderPublicProfile(){const p=publicProfile||{};$('profileIntro').value=p.short_intro||'';$('profileMenuName').value=p.featured_menu_name||'';$('profileMenuPrice').value=p.featured_menu_price??'';$('profileBenefit').value=p.today_benefit||'';$('profileBenefitUntil').value=p.benefit_until||'';$('profilePublished').checked=Boolean(p.is_published);$('profilePublishBadge').textContent=p.is_published?'공개 중':'비공개';$('profilePublishBadge').className=`badge ${p.is_published?'confirmed':''}`;setProfilePreview(profileHeroRemoved?null:p.hero_image_url);$('profileHero').value='';}
function renderInsights(){const t=storeInsights?.totals||{};$('insightDetail').textContent=Number(t.detail_open||0).toLocaleString('ko-KR');$('insightDirections').textContent=Number(t.directions_click||0).toLocaleString('ko-KR');$('insightRecommend').textContent=Number(t.recommendation_click||0).toLocaleString('ko-KR');$('insightBenefit').textContent=Number(t.benefit_click||0).toLocaleString('ko-KR');$('insightPeriod').textContent=storeInsights?`최근 ${storeInsights.days||7}일`:'최근 7일';const total=Number(t.detail_open||0)+Number(t.directions_click||0)+Number(t.recommendation_click||0)+Number(t.benefit_click||0);setStatus('insightStatus',storeInsights?(total?`최근 ${storeInsights.days||7}일 동안 익명 상호작용 ${total.toLocaleString('ko-KR')}건이 집계되었습니다.`:'아직 집계된 상권지도 반응이 없습니다. 방문자가 가게를 탐색하면 여기에 쌓입니다.'):'반응 지표를 불러오지 못했습니다. 잠시 후 새로고침해 주세요.',storeInsights?'':'warn');}
async function uploadProfileHero(file){if(!file)return null;if(file.size>5242880)throw new Error('image_too_large');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('image_type');const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg',path=`${currentStoreId}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from(MEDIA_BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;return sb.storage.from(MEDIA_BUCKET).getPublicUrl(path).data.publicUrl;}
async function savePublicProfile(){const button=$('savePublicProfile'),file=$('profileHero').files?.[0],menuPrice=$('profileMenuPrice').value.trim()===''?null:Number($('profileMenuPrice').value);if(menuPrice!==null&&(!Number.isInteger(menuPrice)||menuPrice<0))return setStatus('profileStatus','대표메뉴 가격을 정확히 입력해 주세요.','warn');button.disabled=true;setStatus('profileStatus','상권지도 공개 카드를 저장하고 있습니다.');try{let hero=profileHeroRemoved?null:(publicProfile?.hero_image_url||null);if(file)hero=await uploadProfileHero(file);const payload={store_id:currentStoreId,hero_image_url:hero,short_intro:$('profileIntro').value.trim()||null,featured_menu_name:$('profileMenuName').value.trim()||null,featured_menu_price:menuPrice,today_benefit:$('profileBenefit').value.trim()||null,benefit_until:$('profileBenefitUntil').value||null,is_published:$('profilePublished').checked};const {data,error}=await sb.from(PROFILE_TABLE).upsert(payload,{onConflict:'store_id'}).select('*').single();if(error)throw error;publicProfile=data;profileHeroRemoved=false;renderPublicProfile();setStatus('profileStatus',payload.is_published?'저장했습니다. 상권지도에 공개 카드가 반영됩니다.':'저장했습니다. 공개 스위치를 켜기 전까지 상권지도에는 보이지 않습니다.');}catch(e){const msg=e.message==='image_too_large'?'대표사진은 5MB 이하만 등록할 수 있습니다.':e.message==='image_type'?'JPG·PNG·WebP 이미지만 등록할 수 있습니다.':'공개 카드를 저장하지 못했습니다. 점포 권한과 연결 상태를 확인해 주세요.';setStatus('profileStatus',msg,'error')}finally{button.disabled=false}}

function renderReadiness(){if(!readiness){$('readinessBadge').textContent='확인 필요';$('readinessBadge').className='badge';$('readinessList').innerHTML='<div class="empty">준비도 정보를 불러오지 못했습니다.</div>';setStatus('nextAction','준비도 API 연결을 확인해 주세요.','warn');return}const checks=readiness.checks||[];$('readinessBadge').textContent=readiness.ready_for_production?'운영 준비':readiness.ready_for_test?'테스트 준비':'준비 중';$('readinessBadge').className=`badge ${readiness.ready_for_production?'confirmed':''}`;$('readinessList').innerHTML=checks.map(c=>`<div class="check-row"><span class="check-icon ${c.ok?'ok':'wait'}">${c.ok?'✓':'·'}</span><div><b>${esc(c.label)}</b><small>${esc(c.detail)}</small></div></div>`).join('');setStatus('nextAction',`다음 작업: ${readiness.next_action||'E2E 테스트'}`,readiness.ready_for_test?'':'warn');}

function renderPendingMenus(){const pending=dashboard.menu.filter(m=>m.verification_status==='pending');$('pendingCount').textContent=`${pending.length}개`;$('pendingMenus').innerHTML=pending.length?pending.map(m=>`<article class="menu-item pending-menu" data-id="${esc(m.id)}"><div class="row between"><div><h3>${esc(m.name)}</h3><small class="muted">기존 메뉴판에서 가져옴 · ${m.price_channel==='direct'?'직접주문 가격':'가격 채널 확인 필요'}</small></div><span class="badge preparing">확인 대기</span></div><div class="grid verify-grid"><div><label>확인 가격</label><input class="verify-price" type="number" min="1" step="100" value="${Number(m.price)}" inputmode="numeric"/></div><div><label>가격 채널</label><select class="verify-channel"><option value="direct" ${m.price_channel==='direct'?'selected':''}>QR·전화·직접주문</option><option value="takeout">포장</option><option value="dine_in">매장</option><option value="delivery">배달</option></select></div></div><div class="row"><button class="approve-menu">가격 확인 · 판매 승인</button><button class="secondary reject-menu">사용하지 않음</button></div></article>`).join(''):'<div class="empty">확인 대기 메뉴가 없습니다.</div>';$('pendingMenus').querySelectorAll('.approve-menu').forEach(b=>b.onclick=async()=>{const card=b.closest('.pending-menu'),price=Number(card.querySelector('.verify-price').value),priceChannel=card.querySelector('.verify-channel').value;if(!Number.isInteger(price)||price<=0)return alert('현재 판매가격을 확인해 입력해 주세요.');if(!confirm(`${won(price)}을 현재 ${priceChannel==='delivery'?'배달':'직접주문'} 가격으로 승인할까요? 승인 즉시 판매메뉴로 전환됩니다.`))return;b.disabled=true;try{await api('/menu-verify',{method:'POST',body:JSON.stringify({store_id:currentStoreId,id:card.dataset.id,decision:'approve',price,price_channel:priceChannel})});await loadDashboard()}catch{alert('메뉴 승인을 완료하지 못했습니다.')}finally{b.disabled=false}});$('pendingMenus').querySelectorAll('.reject-menu').forEach(b=>b.onclick=async()=>{const card=b.closest('.pending-menu');if(!confirm('이 가져온 메뉴를 사용하지 않음으로 처리할까요?'))return;b.disabled=true;try{await api('/menu-verify',{method:'POST',body:JSON.stringify({store_id:currentStoreId,id:card.dataset.id,decision:'reject'})});await loadDashboard()}catch{alert('처리하지 못했습니다.')}finally{b.disabled=false}});}

function renderMenu(){const verified=dashboard.menu.filter(m=>m.verification_status==='verified');$('menuList').innerHTML=verified.length?verified.map(m=>`<article class="menu-item"><div class="row between"><div><h3>${esc(m.name)}</h3><span class="price">${won(m.price)}</span> <span class="badge">${m.price_channel==='delivery'?'배달':m.price_channel==='dine_in'?'매장':m.price_channel==='takeout'?'포장':'직접주문'}</span> ${m.is_available?'':'<span class="badge">판매중지</span>'}</div><div class="row"><button class="ghost edit-menu" data-id="${esc(m.id)}">수정</button><button class="danger delete-menu" data-id="${esc(m.id)}">삭제</button></div></div>${m.description?`<p class="muted">${esc(m.description)}</p>`:''}</article>`).join(''):'<div class="empty">승인된 판매 메뉴가 없습니다. 위의 가져온 메뉴 가격을 먼저 확인하거나 새 메뉴를 등록해 주세요.</div>';$('menuList').querySelectorAll('.edit-menu').forEach(b=>b.onclick=()=>openMenuForm(dashboard.menu.find(m=>m.id===b.dataset.id)));$('menuList').querySelectorAll('.delete-menu').forEach(b=>b.onclick=async()=>{if(!confirm('이 메뉴를 삭제할까요?'))return;try{await api(`/menu/${encodeURIComponent(b.dataset.id)}?store_id=${encodeURIComponent(currentStoreId)}`,{method:'DELETE'});await loadDashboard()}catch{setStatus('menuStatus','메뉴를 삭제하지 못했습니다.','error')}});}
function openMenuForm(item=null){editingMenu=item;$('menuName').value=item?.name||'';$('menuPrice').value=item?.price??'';$('menuDescription').value=item?.description||'';$('menuAvailable').checked=item?.is_available!==false;show('menuForm',true);$('menuName').focus();}
function closeMenuForm(){editingMenu=null;show('menuForm',false)}

const statusLabel={pending:'결제 대기',confirmed:'결제완료',preparing:'준비중',ready:'준비완료',completed:'완료',cancelled:'취소'};
function orderAction(o){if(o.status==='confirmed')return ['preparing','준비 시작'];if(o.status==='preparing')return ['ready','준비 완료'];if(o.status==='ready')return ['completed','수령 완료'];if(o.status==='pending'&&!o.payment?.status)return ['cancelled','미결제 주문 취소'];return null;}
function renderOrders(){$('orders').innerHTML=dashboard.orders.length?dashboard.orders.map(o=>{const action=orderAction(o),paid=['paid','partially_cancelled'].includes(o.payment?.status);return `<article class="order" data-id="${esc(o.id)}"><div class="row between"><div><span class="badge ${esc(o.status)}">${esc(statusLabel[o.status]||o.status)}</span><h3 style="margin-top:8px">${esc(o.order_no)}</h3></div><strong>${won(o.total)}</strong></div><p class="muted">${new Date(o.created_at).toLocaleString('ko-KR')} · ${o.fulfillment_type==='table'?`테이블 ${esc(o.table_ref||'')}`:'포장'} · ${esc(o.customer_name||'')}</p><div class="order-lines">${(o.items||[]).map(i=>`<div><span>${esc(i.item_name)} × ${i.quantity}</span><strong>${won(i.line_total)}</strong></div>`).join('')}</div><div class="row">${action?`<button class="order-next" data-next="${action[0]}">${action[1]}</button>`:''}${paid?`<button class="danger refund" data-payment="${esc(o.payment.id)}">${o.payment.status==='paid'?'전체 환불':'추가 환불 문의'}</button>`:''}<span class="muted">결제: ${esc(o.payment?.status||'미완료')}</span></div></article>`}).join(''):'<div class="empty">아직 주문이 없습니다.</div>';$('orders').querySelectorAll('.order-next').forEach(b=>b.onclick=async()=>{const orderId=b.closest('.order').dataset.id;b.disabled=true;try{await api('/order-status',{method:'POST',body:JSON.stringify({order_id:orderId,status:b.dataset.next})});await loadDashboard()}catch(e){alert(e.message==='paid_order_requires_refund'?'결제된 주문은 환불 후 취소할 수 있습니다.':'주문 상태를 변경하지 못했습니다.')}finally{b.disabled=false}});$('orders').querySelectorAll('.refund').forEach(b=>b.onclick=async()=>{if(b.textContent.includes('문의'))return alert('부분환불 후 추가 처리는 운영자 확인이 필요합니다.');if(!confirm('결제를 전체 환불하시겠습니까? 이 작업은 실제 PG 취소를 요청합니다.'))return;const reason=prompt('환불 사유를 입력해 주세요.','고객 요청')||'고객 요청';b.disabled=true;try{await api('',{method:'POST',body:JSON.stringify({payment_id:b.dataset.payment,reason})},PAYMENT_ADMIN);await loadDashboard()}catch{alert('환불을 완료하지 못했습니다. 결제 상태를 확인해 주세요.')}finally{b.disabled=false}});}

$('sendLink').onclick=async()=>{const email=$('email').value.trim();if(!email)return;$('sendLink').disabled=true;try{const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:absolute('/store-admin'),shouldCreateUser:true}});if(error)throw error;setStatus('loginStatus','로그인 링크를 보냈습니다.')}catch{setStatus('loginStatus','로그인 링크를 보내지 못했습니다. 운영 도메인/Auth 설정을 확인해 주세요.','error')}finally{$('sendLink').disabled=false}};
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};$('refresh').onclick=loadDashboard;$('storeSelect').onchange=async e=>{currentStoreId=e.target.value;await loadDashboard()};$('newMenu').onclick=()=>openMenuForm();$('cancelMenu').onclick=closeMenuForm;
$('profileHero').addEventListener('change',()=>{const file=$('profileHero').files?.[0];if(!file)return setProfilePreview(profileHeroRemoved?null:publicProfile?.hero_image_url);profileHeroRemoved=false;setProfilePreview(URL.createObjectURL(file));});
$('profileImageClear').onclick=()=>{profileHeroRemoved=true;$('profileHero').value='';setProfilePreview(null);setStatus('profileStatus','대표사진을 제거하려면 공개 카드 저장을 눌러 주세요.','warn')};
$('savePublicProfile').onclick=savePublicProfile;
$('saveMenu').onclick=async()=>{const name=$('menuName').value.trim(),price=Number($('menuPrice').value);if(!name||!Number.isInteger(price)||price<0)return setStatus('menuStatus','메뉴명과 정확한 가격을 입력해 주세요.','warn');$('saveMenu').disabled=true;try{await api('/menu',{method:'POST',body:JSON.stringify({id:editingMenu?.id,store_id:currentStoreId,name,price,description:$('menuDescription').value.trim(),is_available:$('menuAvailable').checked,price_channel:editingMenu?.price_channel||'direct'})});closeMenuForm();await loadDashboard()}catch{setStatus('menuStatus','메뉴를 저장하지 못했습니다.','error')}finally{$('saveMenu').disabled=false}};
$('toggleOrdering').onclick=async()=>{const enabled=!dashboard.store.order_enabled;if(enabled&&!confirm('온라인 주문을 켤까요? 검증된 메뉴와 PG 설정이 모두 준비된 경우에만 열립니다.'))return;$('toggleOrdering').disabled=true;try{const d=await api('/ordering',{method:'POST',body:JSON.stringify({store_id:currentStoreId,enabled})});if(d.target_path)setStatus('storeStatus',`주문이 열렸습니다. QR 연결주소: ${absolute(d.target_path)}`);await loadDashboard()}catch(e){const msg=e.message==='verified_menu_required'?'가격 확인이 완료된 판매메뉴가 먼저 필요합니다.':e.message==='payment_configuration_required'?'매장 PG 설정이 완료되어야 주문을 켤 수 있습니다.':'주문 상태를 변경하지 못했습니다.';setStatus('storeStatus',msg,'error')}finally{$('toggleOrdering').disabled=false}};

const {data:{session:initial}}=await sb.auth.getSession();if(initial){show('loginCard',false);await loadStores()}else show('loginCard',true);
sb.auth.onAuthStateChange(async(event,s)=>{if(event==='SIGNED_IN'&&s){show('loginCard',false);await loadStores()}if(event==='SIGNED_OUT'){show('app',false);show('loginCard',true)}});
