import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://renzehysxirjilvdxacv.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_';
const STORE_API=`${SUPABASE_URL}/functions/v1/store-api`;
const PAYMENT_ADMIN=`${SUPABASE_URL}/functions/v1/payment-admin`;
const sb=createClient(SUPABASE_URL,PUBLISHABLE_KEY,{auth:{flowType:'pkce',detectSessionInUrl:true,persistSession:true}});
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const won=n=>`${Number(n||0).toLocaleString('ko-KR')}원`;
let stores=[],currentStoreId=null,dashboard=null,editingMenu=null;
function show(id,on=true){$(id).classList.toggle('hide',!on)}
function setStatus(id,text,type=''){const e=$(id);e.textContent=text;e.className=`status${type?` ${type}`:''}`;e.classList.remove('hide')}
async function session(){const {data}=await sb.auth.getSession();return data.session}
async function api(path,options={},base=STORE_API){const s=await session();if(!s)throw new Error('login_required');const headers={apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${s.access_token}`,...(options.headers||{})};if(options.body)headers['content-type']='application/json';const r=await fetch(`${base}${path}`,{...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data.error||`http_${r.status}`);e.data=data;e.status=r.status;throw e}return data;}

async function loadStores(){const d=await api('/stores');stores=d.stores||[];if(!stores.length){show('app',false);setStatus('loginStatus','승인된 점포가 없습니다. 먼저 정회원 페이지에서 내 가게 확인 신청을 완료해 주세요.','warn');show('loginCard',true);return}const select=$('storeSelect');select.innerHTML=stores.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');show('storeSelect',stores.length>1);show('refresh',true);show('logout',true);currentStoreId=currentStoreId&&stores.some(s=>s.id===currentStoreId)?currentStoreId:stores[0].id;select.value=currentStoreId;await loadDashboard();}
async function loadDashboard(){if(!currentStoreId)return;const d=await api(`/dashboard?store_id=${encodeURIComponent(currentStoreId)}`);dashboard=d;show('loginCard',false);show('app',true);renderDashboard();}

function renderDashboard(){const d=dashboard,s=d.store;$('storeName').textContent=s.name;$('storeAddress').textContent=s.public_address||'';const today=new Date().toISOString().slice(0,10);const todays=d.orders.filter(o=>String(o.created_at).slice(0,10)===today);$('todayOrders').textContent=todays.length;$('paidOrders').textContent=d.orders.filter(o=>o.payment?.status==='paid').length;$('activeOrders').textContent=d.orders.filter(o=>['confirmed','preparing','ready'].includes(o.status)).length;$('menuCount').textContent=d.menu.filter(m=>m.is_available).length;$('orderBadge').textContent=s.order_enabled?'주문 ON':'주문 OFF';$('orderBadge').className=`badge ${s.order_enabled?'confirmed':''}`;$('toggleOrdering').textContent=s.order_enabled?'주문 끄기':'주문 켜기';setStatus('storeStatus',s.order_enabled?'온라인 주문이 열려 있습니다.':'온라인 주문은 현재 닫혀 있습니다.',s.order_enabled?'':'warn');const storeQr=d.qr_codes.find(q=>q.kind==='store'&&q.active);if(storeQr){const url=`${location.origin}/order/${encodeURIComponent(s.slug)}?qr=${encodeURIComponent(storeQr.code)}&source=store-qr`;$('qrBox').innerHTML=`<b>매장 QR 연결주소</b><br><a href="${esc(url)}" target="_blank" rel="noopener">${esc(url)}</a>`;show('qrBox',true);$('openOrder').href=url;show('openOrder',true)}else{show('qrBox',false);$('openOrder').href=`/order/${encodeURIComponent(s.slug)}`;show('openOrder',s.order_enabled)}renderMenu();renderOrders();}

function renderMenu(){$('menuList').innerHTML=dashboard.menu.length?dashboard.menu.map(m=>`<article class="menu-item"><div class="row between"><div><h3>${esc(m.name)}</h3><span class="price">${won(m.price)}</span> ${m.is_available?'':'<span class="badge">판매중지</span>'}</div><div class="row"><button class="ghost edit-menu" data-id="${esc(m.id)}">수정</button><button class="danger delete-menu" data-id="${esc(m.id)}">삭제</button></div></div>${m.description?`<p class="muted">${esc(m.description)}</p>`:''}</article>`).join(''):'<div class="empty">등록된 메뉴가 없습니다. 메뉴와 PG 설정이 있어야 주문을 켤 수 있습니다.</div>';$('menuList').querySelectorAll('.edit-menu').forEach(b=>b.onclick=()=>openMenuForm(dashboard.menu.find(m=>m.id===b.dataset.id)));$('menuList').querySelectorAll('.delete-menu').forEach(b=>b.onclick=async()=>{if(!confirm('이 메뉴를 삭제할까요?'))return;try{await api(`/menu/${encodeURIComponent(b.dataset.id)}?store_id=${encodeURIComponent(currentStoreId)}`,{method:'DELETE'});await loadDashboard()}catch{setStatus('menuStatus','메뉴를 삭제하지 못했습니다.','error')}});}
function openMenuForm(item=null){editingMenu=item;$('menuName').value=item?.name||'';$('menuPrice').value=item?.price??'';$('menuDescription').value=item?.description||'';$('menuAvailable').checked=item?.is_available!==false;show('menuForm',true);$('menuName').focus();}
function closeMenuForm(){editingMenu=null;show('menuForm',false)}

const statusLabel={pending:'결제 대기',confirmed:'결제완료',preparing:'준비중',ready:'준비완료',completed:'완료',cancelled:'취소'};
function orderAction(o){if(o.status==='confirmed')return ['preparing','준비 시작'];if(o.status==='preparing')return ['ready','준비 완료'];if(o.status==='ready')return ['completed','수령 완료'];if(o.status==='pending'&&!o.payment?.status)return ['cancelled','미결제 주문 취소'];return null;}
function renderOrders(){$('orders').innerHTML=dashboard.orders.length?dashboard.orders.map(o=>{const action=orderAction(o),paid=['paid','partially_cancelled'].includes(o.payment?.status);return `<article class="order" data-id="${esc(o.id)}"><div class="row between"><div><span class="badge ${esc(o.status)}">${esc(statusLabel[o.status]||o.status)}</span><h3 style="margin-top:8px">${esc(o.order_no)}</h3></div><strong>${won(o.total)}</strong></div><p class="muted">${new Date(o.created_at).toLocaleString('ko-KR')} · ${o.fulfillment_type==='table'?`테이블 ${esc(o.table_ref||'')}`:'포장'} · ${esc(o.customer_name||'')}</p><div class="order-lines">${(o.items||[]).map(i=>`<div><span>${esc(i.item_name)} × ${i.quantity}</span><strong>${won(i.line_total)}</strong></div>`).join('')}</div><div class="row">${action?`<button class="order-next" data-next="${action[0]}">${action[1]}</button>`:''}${paid?`<button class="danger refund" data-payment="${esc(o.payment.id)}">${o.payment.status==='paid'?'전체 환불':'추가 환불 문의'}</button>`:''}<span class="muted">결제: ${esc(o.payment?.status||'미완료')}</span></div></article>`}).join(''):'<div class="empty">아직 주문이 없습니다.</div>';$('orders').querySelectorAll('.order-next').forEach(b=>b.onclick=async()=>{const orderId=b.closest('.order').dataset.id;b.disabled=true;try{await api('/order-status',{method:'POST',body:JSON.stringify({order_id:orderId,status:b.dataset.next})});await loadDashboard()}catch(e){alert(e.message==='paid_order_requires_refund'?'결제된 주문은 환불 후 취소할 수 있습니다.':'주문 상태를 변경하지 못했습니다.')}finally{b.disabled=false}});$('orders').querySelectorAll('.refund').forEach(b=>b.onclick=async()=>{if(b.textContent.includes('문의'))return alert('부분환불 후 추가 처리는 운영자 확인이 필요합니다.');if(!confirm('결제를 전체 환불하시겠습니까? 이 작업은 실제 PG 취소를 요청합니다.'))return;const reason=prompt('환불 사유를 입력해 주세요.','고객 요청')||'고객 요청';b.disabled=true;try{await api('',{method:'POST',body:JSON.stringify({payment_id:b.dataset.payment,reason})},PAYMENT_ADMIN);await loadDashboard()}catch{alert('환불을 완료하지 못했습니다. 결제 상태를 확인해 주세요.')}finally{b.disabled=false}});}

$('sendLink').onclick=async()=>{const email=$('email').value.trim();if(!email)return;$('sendLink').disabled=true;try{const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/store-admin`,shouldCreateUser:true}});if(error)throw error;setStatus('loginStatus','로그인 링크를 보냈습니다.')}catch{setStatus('loginStatus','로그인 링크를 보내지 못했습니다. 운영 도메인/Auth 설정을 확인해 주세요.','error')}finally{$('sendLink').disabled=false}};
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};$('refresh').onclick=loadDashboard;$('storeSelect').onchange=async e=>{currentStoreId=e.target.value;await loadDashboard()};$('newMenu').onclick=()=>openMenuForm();$('cancelMenu').onclick=closeMenuForm;
$('saveMenu').onclick=async()=>{const name=$('menuName').value.trim(),price=Number($('menuPrice').value);if(!name||!Number.isInteger(price)||price<0)return setStatus('menuStatus','메뉴명과 정확한 가격을 입력해 주세요.','warn');$('saveMenu').disabled=true;try{await api('/menu',{method:'POST',body:JSON.stringify({id:editingMenu?.id,store_id:currentStoreId,name,price,description:$('menuDescription').value.trim(),is_available:$('menuAvailable').checked})});closeMenuForm();await loadDashboard()}catch{setStatus('menuStatus','메뉴를 저장하지 못했습니다.','error')}finally{$('saveMenu').disabled=false}};
$('toggleOrdering').onclick=async()=>{const enabled=!dashboard.store.order_enabled;if(enabled&&!confirm('온라인 주문을 켤까요? 메뉴와 PG 설정이 검증된 경우에만 열립니다.'))return;$('toggleOrdering').disabled=true;try{const d=await api('/ordering',{method:'POST',body:JSON.stringify({store_id:currentStoreId,enabled})});if(d.target_path)setStatus('storeStatus',`주문이 열렸습니다. QR 연결주소: ${location.origin}${d.target_path}`);await loadDashboard()}catch(e){const msg=e.message==='menu_required'?'주문 가능한 메뉴를 먼저 등록해 주세요.':e.message==='payment_configuration_required'?'PG 설정이 완료되어야 주문을 켤 수 있습니다.':'주문 상태를 변경하지 못했습니다.';setStatus('storeStatus',msg,'error')}finally{$('toggleOrdering').disabled=false}};

const {data:{session:initial}}=await sb.auth.getSession();if(initial){show('loginCard',false);await loadStores()}else show('loginCard',true);
sb.auth.onAuthStateChange(async(event,s)=>{if(event==='SIGNED_IN'&&s){show('loginCard',false);await loadStores()}if(event==='SIGNED_OUT'){show('app',false);show('loginCard',true)}});
