name = "cgma-root-gateway"
main = "cgma-root-gateway.js"
compatibility_date = "2026-08-15"
workers_dev = false

routes = [
  { pattern = "ekodi.kr/cgma*", zone_name = "ekodi.kr" }
]

[[services]]
binding = "EKODI_SHARED"
service = "shy-thunder-39a4"
