import {cleanStoreValue,storeAliasKey,canonicalStoreKey,ensureStoreEvents,recordStoreAlias,aliasesForStore,storeIdForAlias} from '../_shared/cgma-store-identity.js';
const STORE_API='https://renzehysxirjilvdxacv.supabase.co/functions/v1/store-api',SUPABASE_URL='https://renzehysxirjilvdxacv.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_0QjB0WzZbjrd-FJ5D5cR7A_xUkXyOY_';
const EVENT_TYPES=new Set(['detail_open','directions_click','benefit_click','recommendation_click']);
const clean=(value,max)=>cleanStoreValue(value,max),reply=(body,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
function originAllowed(value){if(!value)return true;try{const url=new URL(value),host=url.hostname.toLowerCase();if(url.protocol==='https:'&&['cgma.or.kr','www.cgma.or.kr','ekodi.kr','www.ekodi.kr'].includes(host))return true;return url.protocol==='http:'&&['127.0.0.1','localhost'].includes(host);}catch{return false;}}
function koreaDay(offset=0){const d=new Date(Date.now()-offset*86400000),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d),o=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`;}
async function authorizedStore(request,storeId){const auth=request.headers.get('authorization')||'';if(!/^Bearer\s+\S+/i.test(auth)||!storeId)return null;const r=await fetch(`${STORE_API}/stores`,{headers:{apikey:PUBLISHABLE_KEY,Authorization:auth}});if(!r.ok)return null;const data=await r.json().catch(()=>({}));return (data.stores||[]).find(store=>String(store.id)===String(storeId))||null;}
async function verifiedPublicStoreId(storeId,storeName){const id=clean(storeId,80),alias=storeAliasKey(storeName);if(!id||!alias)return null;const url=`${SUPABASE_URL}/rest/v1/store_public_profiles?select=store_id,store_name&store_id=eq.${encodeURIComponent(id)}&is_published=eq.true&limit=1`;const r=await fetch(url,{headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${PUBLISHABLE_KEY}`}}).catch(()=>null);if(!r?.ok)return null;const row=(await r.json().catch(()=>[]))[0];return row&&storeAliasKey(row.store_name)===alias?String(row.store_id):null;}
export async function onRequestPost({request,env}){
 const db=env.cheonggye_market_notices;if(!db)return reply({error:'analytics_store_unavailable'},503);await ensureStoreEvents(db);const origin=request.headers.get('origin')||'';if(!originAllowed(origin))return reply({error:'origin_not_allowed'},403);
 let body;try{body=await request.json()}catch{return reply({error:'invalid_json'},400)}if(clean(body.website,120))return reply({ok:true},202);
 const storeName=clean(body.store_name,120),alias=storeAliasKey(storeName),eventType=clean(body.event_type,40),source=clean(body.source,50).toLowerCase().replace(/[^a-z0-9_-]/g,'');if(!alias||!EVENT_TYPES.has(eventType)||!source)return reply({error:'invalid_event'},400);
 const verifiedId=await verifiedPublicStoreId(body.store_id,storeName);if(verifiedId)await recordStoreAlias(db,verifiedId,storeName);const storeId=verifiedId||await storeIdForAlias(db,alias),key=storeId?canonicalStoreKey(storeId):alias;
 await db.prepare(`INSERT INTO cgma_store_events(day,store_id,store_key,store_name,event_type,source,count) VALUES(?,?,?,?,?,?,1) ON CONFLICT(day,store_key,event_type,source) DO UPDATE SET count=count+1,store_id=excluded.store_id,store_name=excluded.store_name,updated_at=CURRENT_TIMESTAMP`).bind(koreaDay(),storeId,key,storeName,eventType,source).run();return reply({ok:true},202);
}
export async function onRequestGet({request,env}){
 const db=env.cheonggye_market_notices;if(!db)return reply({error:'analytics_store_unavailable'},503);await ensureStoreEvents(db);const url=new URL(request.url),storeId=clean(url.searchParams.get('store_id'),80),days=Math.min(30,Math.max(1,Number(url.searchParams.get('days'))||7)),store=await authorizedStore(request,storeId);if(!store)return reply({error:'store_access_required'},403);
 await recordStoreAlias(db,store.id,store.name);const keys=[canonicalStoreKey(store.id),...await aliasesForStore(db,store.id,store.name)],from=koreaDay(days-1),marks=keys.map(()=>'?').join(','),result=await db.prepare(`SELECT day,event_type,source,SUM(count) AS count FROM cgma_store_events WHERE (store_id=? OR store_key IN (${marks})) AND day>=? GROUP BY day,event_type,source ORDER BY day DESC`).bind(store.id,...keys,from).all();
 const totals={detail_open:0,directions_click:0,benefit_click:0,recommendation_click:0},daily={};for(const row of result.results||[]){const n=Number(row.count||0);if(row.event_type in totals)totals[row.event_type]+=n;(daily[row.day]??={detail_open:0,directions_click:0,benefit_click:0,recommendation_click:0})[row.event_type]=(daily[row.day]?.[row.event_type]||0)+n;}
 return reply({store:{id:store.id,name:store.name},days,from,to:koreaDay(),totals,daily:Object.entries(daily).map(([day,counts])=>({day,...counts})),identity:'store_id'});
}
